browserType=edge
baseUrl=https://www.saucedemo.com/
userNameLocator=user-name
passwordLocator=password
loginButtonLocator=login-button
scBackBagLocator=add-to-cart-sauce-labs-backpack
cartProductQuantityLocator =#shopping_cart_container > a > span
scBikeLightLocator=add-to-cart-sauce-labs-bike-light
scBoltTShirtLocator=add-to-cart-sauce-labs-bolt-t-shirt
scFleeceJacketLocator=add-to-cart-sauce-labs-fleece-jacket
scOnesieLocator=add-to-cart-sauce-labs-onesie
scRedTShirtLocator=add-to-cart-test.allthethings()-t-shirt-(red)
sl_BackButtonRemoveLocator=remove-sauce-labs-backpack
sl_BikeLightRemoveLocator=remove-sauce-labs-bike-light
sl_BoltTShirtRemoveLocator=remove-sauce-labs-bolt-t-shirt
sl_FleeceJacketRemoveLocator=remove-sauce-labs-fleece-jacket
sl_OnesieRemoveLocator=remove-sauce-labs-onesie
sl_RedTShirtRemoveLocator=remove-test.allthethings()-t-shirt-(red)
imgBackBagLocator= [src="/static/media/sauce-backpack-1200x1500.0a0b85a385945026062b.jpg"]
normalHeaderBackBagLocator=#item_4_title_link > div
detailedHeaderBackBagLocator=#inventory_item_container > div > div > div.inventory_details_desc_container > div.inventory_details_name.large_size
paragraphBackBagLocator=#inventory_item_container > div > div > div.inventory_details_desc_container > div.inventory_details_desc.large_size
priceBackBagLocator=#inventory_item_container > div > div > div.inventory_details_desc_container > div.inventory_details_price
imgBikeLightLocator=[src="/static/media/bike-light-1200x1500.37c843b09a7d77409d63.jpg"]
normalHeaderBikeLightLocator=#item_0_title_link > div
detailedHeaderBikeLightLocator=#inventory_item_container > div > div > div.inventory_details_desc_container > div.inventory_details_name.large_size
paragraphBikeLightLocator=#inventory_item_container > div > div > div.inventory_details_desc_container > div.inventory_details_desc.large_size
priceBikeLightLocator=#inventory_item_container > div > div > div.inventory_details_desc_container > div.inventory_details_price
imgBoltTShirtLocator=[src="/static/media/bolt-shirt-1200x1500.c2599ac5f0a35ed5931e.jpg"]
normalHeaderBoltTShirtLocator=#item_1_title_link > div
detailedHeaderBoltTShirtLocator=#inventory_item_container > div > div > div.inventory_details_desc_container > div.inventory_details_name.large_size
paragraphBoltTShirtLocator=#inventory_item_container > div > div > div.inventory_details_desc_container > div.inventory_details_desc.large_size
priceBoltTShirtLocator=#inventory_item_container > div > div > div.inventory_details_desc_container > div.inventory_details_price
imgFleeceJacketLocator=[src="/static/media/sauce-pullover-1200x1500.51d7ffaf301e698772c8.jpg"]
normalHeaderFleeceJacketLocator=#item_5_title_link > div
detailedHeaderFleeceJacketLocator=#inventory_item_container > div > div > div.inventory_details_desc_container > div.inventory_details_name.large_size
paragraphFleeceJacketLocator=#inventory_item_container > div > div > div.inventory_details_desc_container > div.inventory_details_desc.large_size
priceFleeceJacketLocator=#inventory_item_container > div > div > div.inventory_details_desc_container > div.inventory_details_price
imgOnesieLocator=[src="/static/media/red-onesie-1200x1500.2ec615b271ef4c3bc430.jpg"]
normalHeaderOnesieLocator=#item_2_title_link > div
detailedHeaderOnesieLocator=#inventory_item_container > div > div > div.inventory_details_desc_container > div.inventory_details_name.large_size
paragraphOnesieLocator=#inventory_item_container > div > div > div.inventory_details_desc_container > div.inventory_details_desc.large_size
priceOnesieLocator=#inventory_item_container > div > div > div.inventory_details_desc_container > div.inventory_details_price
imgRedTShirtLocator=[src="/static/media/red-tatt-1200x1500.30dadef477804e54fc7b.jpg"]   
normalHeaderRedTShirtLocator=#item_3_title_link > div
detailedHeaderRedTShirtLocator=#inventory_item_container > div > div > div.inventory_details_desc_container > div.inventory_details_name.large_size
paragraphRedTShirtLocator=#inventory_item_container > div > div > div.inventory_details_desc_container > div.inventory_details_desc.large_size
priceRedTShirtLocator=#inventory_item_container > div > div > div.inventory_details_desc_container > div.inventory_details_price
cartButtonLocator=#shopping_cart_container > a
checkoutButtonLocator=[name="checkout"]
firstNameLabelLocator=[name="firstName"]
lastNameLabelLocator=[name="lastName"]
zip_postalCodeLocators=[name="postalCode"]
cancelButtonLocator=[name="cancel"]
continueButtonLocator=[name="continue"]
errorMessageLocator=#checkout_info_container > div > form > div.checkout_info > div.error-message-container.error > h3
cartIconLocator=[data-test="shopping-cart-link"]
twitterIconLocator=[data-test="social-twitter"]
faceBookIconLocator=[data-test="social-facebook"]
linkidINIconLocator=[data-test="social-linkedin"]
hamburgerButtonLocator=[id="react-burger-menu-btn"]
aboutLinkLocator=[data-test="about-sidebar-link"]
logoutLinkLocator=[id="logout_sidebar_link"]
finishButtonLocator=[name="finish"]
cancellButtonLocator=[data-test="cancel"]
BackBagPriceLocator=#checkout_summary_container > div > div.cart_list > div:nth-child(3)>div>div>div
bikeLightPriceLocator=/html/body/div/div/div/div[2]/div/div[1]/div[4]/div[2]/div[2]/div
totalNetitemspriceLocator= #checkout_summary_container > div > div.summary_info > div.summary_subtotal_label
totalTaxLocator=#checkout_summary_container > div > div.summary_info > div.summary_tax_label
totalLocator= #checkout_summary_container > div > div.summary_info > div.summary_total_label
backBagHeaderLocator= #checkout_summary_container > div > div.cart_list > div:nth-child(3)>div>a
backBagBaragrapghLocator=[data-test='inventory-item-desc']
bikeLightHeaderLocator=#item_0_title_link > div
bikeLightParagrapghLocator=/html/body/div/div/div/div[2]/div/div[1]/div[4]/div[2]/div[1]
correctMarkLocator=[data-test="pony-express"]
thanksMessageLocator=[data-test="complete-header"]
paraghraghLocator=[data-test="complete-text"]
backHomeButtonLocator=[data-test="back-to-products"]
expectedmsgForInvalidusernameOrpasswordLocator=//h3[@data-test='error']
expectedmsgForEmptyusernameOrpasswordLocator=h3[data-test='error']
removeProductFromCartLocator=[name="remove-sauce-labs-backpack"]
continueShoppingBtnLocator=[name="continue-shopping"]
Header_BackbagcartLocator=a[id='item_4_title_link'] div[class='inventory_item_name']
paragraphBackbagcartLocator=[data-test="inventory-item-desc"]
priceBackbagcartLocator=div[class='inventory_item_price']
dropDownLocator=product_sort_container
productNameLocator=inventory_item_name
productPriceLocator=inventory_item_price
cartBadgeLocator = #shopping_cart_container > a > span
errormessageLockedLocator=[data-test='error']








