validUsername=standard_user
validPassword=secret_sauce
invalidUsername=fatma
invalidPassword=admin
spaceUsername=standard _user
expectedUrl=https://www.saucedemo.com/inventory.html
validfirstName=mohamed
validlastName=ahmed
validzipCode=12345
firstNameDigits=1234
lastNameDigits=1234
zipCodeletter=asdcx
firstName1letter=a
lastName1letter=a
zipCode1digit=1
spacePassword=secret _sauce
lockedUser=locked_out_user
problemUser=problem_user
performanceGlitchUser=performance_glitch_user
errorUser=error_user
visualUser=visual_user



