validUsername=standard_user
validPassword=secret_sauce
invalidUsername=fatma
invalidPassword=admin
spaceUsername=standard _user
expectedUrl=https://www.saucedemo.com/inventory.html
validfirstName=mohamed
validlastName=ahmed
validzipCode=12345
firstNameDigits=1234
lastNameDigits=1234
zipCodeletter=asdcx
firstName1letter=a
lastName1letter=a
zipCode1digit=1
spacePassword=secret _sauce
lockedUser=locked_out_user
problemUser=problem_user
performanceGlitchUser=performance_glitch_user
errorUser=error_user
visualUser=visual_user
expectedmsgForLockedAcc=Epic sadface: Sorry, this user has been locked out.
expectedmsgForInvalidusernameOrpassword=Epic sadface: Username and password do not match any user in this service
expectedmsgForEmptyusername=Epic sadface: Username is required
expectedmsgForEmptypassword=Epic sadface: Password is required
cartlink=https://www.saucedemo.com/cart.html
overviewlink=https://www.saucedemo.com/checkout-step-two.html
twitterLink=https://x.com/saucelabs
facebookLink=https://web.facebook.com/saucelabs?_rdc=1&_rdr#
linkidInLink=https://www.linkedin.com/company/sauce-labs/
checkOutPageLink=https://www.saucedemo.com/checkout-step-one.html
aboutSauceLabs=https://saucelabs.com/
completeLink=https://www.saucedemo.com/checkout-complete.html
checkoutPageUrl=https://www.saucedemo.com/checkout-step-one.html





